TARGET_HAS_THIRD_PARTY_APPS := true
WPA_SUPPLICANT_VERSION := VER_0_6_X
BOARD_WPA_SUPPLICANT_DRIVER := AWEXT
BOARD_WPA_SUPPLICANT_PRIVATE_LIB :=

BOARD_USES_KBDSENSOR := true
BOARD_USES_KBDSENSOR_ROTKEY2 := true

BOARD_GPU_DRIVERS := r600g

include $(GENERIC_X86_CONFIG_MK)
