TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_WPA_SUPPLICANT_DRIVER := AWEXT
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
BOARD_USES_WACOMINPUT := true
BOARD_USES_TSLIB := true
BUILD_WITH_MPLAYER := true

BOARD_GPU_DRIVERS := r600g

include $(GENERIC_X86_CONFIG_MK)
